#!/usr/bin/env bash
# op-session.sh — 1Password session manager for Claude Code / agentic CLI workflows
#
# This script manages a short-lived 1Password service account session so that
# an AI agent (Claude Code, aider, etc.) can invoke `op run` without ever
# seeing the actual secrets. The service account token itself is fetched once
# via biometric auth and cached in a temp file (mode 0600) under /tmp with a
# rolling timeout.
#
# NOTE: On macOS, /tmp is on APFS (not a RAM filesystem). The token file may
# appear in APFS snapshots or Time Machine backups. The dd-overwrite on session
# end reduces exposure but does not guarantee secure erasure on copy-on-write
# filesystems. For high-sensitivity environments, set OP_SESSION_DIR to a
# RAM-backed path (e.g. a mounted ramfs volume).
#
# SECURITY MODEL:
#   - The SA token is read from your personal vault via `op read` (biometric).
#   - It is written to a temp file (mode 0600) under /tmp, NOT exported to the
#     environment of the calling process.
#   - All secret-consuming commands are executed via `op-session.sh exec`, which
#     injects OP_SERVICE_ACCOUNT_TOKEN only into the child process environment.
#   - The agent never sees the token value or the secret values.
#   - A rolling inactivity timeout (default 2h) auto-expires the session.
#
# USAGE:
#   op-session.sh init                    # Fetch SA token (biometric prompt)
#   op-session.sh exec <command...>       # Run command with secrets injected
#   op-session.sh read <secret-ref>       # Read a secret ref via SA token
#   op-session.sh status                  # Check session state
#   op-session.sh extend                  # Manually reset the timeout
#   op-session.sh end                     # Destroy the session immediately
#
# CONFIGURATION (via env vars or config file):
#   OP_SESSION_SA_REF       — op:// reference to the SA token in your vault
#                             e.g. "op://Private/Claude-SA-Token/credential"
#   OP_SESSION_TIMEOUT      — Inactivity timeout in seconds (default: 7200 = 2h)
#   OP_SESSION_DIR          — Directory for session files (default: /tmp/op-session)
#
# CONFIG FILE:
#   If ~/.config/op-session/config exists, it is sourced (executed) before
#   processing. This lets you set OP_SESSION_SA_REF once instead of per-
#   invocation. The file is generated by op-session-setup.sh with mode 0600.
#   SECURITY: Do not allow other processes to write to this file — sourcing
#   an untrusted config file is equivalent to arbitrary code execution.

set -euo pipefail

# ── Configuration ──────────────────────────────────────────────────────────────

CONFIG_FILE="${HOME}/.config/op-session/config"
if [[ -f "$CONFIG_FILE" ]]; then
    # shellcheck source=/dev/null
    source "$CONFIG_FILE"
fi

OP_SESSION_SA_REF="${OP_SESSION_SA_REF:-}"
OP_SESSION_TIMEOUT="${OP_SESSION_TIMEOUT:-7200}"
OP_SESSION_DIR="${OP_SESSION_DIR:-/tmp/op-session}"

SESSION_TOKEN_FILE="${OP_SESSION_DIR}/sa-token"
SESSION_EXPIRY_FILE="${OP_SESSION_DIR}/expiry"
SESSION_LOCK_FILE="${OP_SESSION_DIR}/lock"

# ── Helpers ────────────────────────────────────────────────────────────────────

die() { echo "op-session: ERROR: $*" >&2; exit 1; }
info() { echo "op-session: $*" >&2; }

ensure_dir() {
    if [[ ! -d "$OP_SESSION_DIR" ]]; then
        mkdir -p "$OP_SESSION_DIR"
        chmod 700 "$OP_SESSION_DIR"
    fi
}

now_epoch() { date +%s; }

read_expiry() {
    if [[ -f "$SESSION_EXPIRY_FILE" ]]; then
        cat "$SESSION_EXPIRY_FILE"
    else
        echo "0"
    fi
}

write_expiry() {
    local new_expiry
    new_expiry=$(( $(now_epoch) + OP_SESSION_TIMEOUT ))
    echo "$new_expiry" > "$SESSION_EXPIRY_FILE"
}

is_session_valid() {
    [[ -f "$SESSION_TOKEN_FILE" ]] || return 1
    [[ -f "$SESSION_EXPIRY_FILE" ]] || return 1
    local expiry
    expiry=$(read_expiry)
    local now
    now=$(now_epoch)
    (( now < expiry ))
}

touch_session() {
    # Rolling timeout: reset expiry on every use
    if is_session_valid; then
        write_expiry
    fi
}

load_token() {
    if ! is_session_valid; then
        die "No active session. Run 'op-session.sh init' first."
    fi
    touch_session
    cat "$SESSION_TOKEN_FILE"
}

cleanup_session() {
    if [[ -f "$SESSION_TOKEN_FILE" ]]; then
        # Overwrite before delete
        dd if=/dev/urandom of="$SESSION_TOKEN_FILE" bs=1024 count=1 2>/dev/null || true
        rm -f "$SESSION_TOKEN_FILE"
    fi
    rm -f "$SESSION_EXPIRY_FILE"
    rm -f "$SESSION_LOCK_FILE"
    info "Session ended and token destroyed."
}

# ── Commands ───────────────────────────────────────────────────────────────────

cmd_init() {
    if [[ -z "$OP_SESSION_SA_REF" ]]; then
        die "OP_SESSION_SA_REF is not set. Configure it in $CONFIG_FILE or export it.
Example: export OP_SESSION_SA_REF='op://Private/Claude-SA-Token/credential'"
    fi

    # Check if there's already a valid session
    if is_session_valid; then
        info "Session already active (expires in $(( $(read_expiry) - $(now_epoch) ))s). Use 'end' first to reset."
        return 0
    fi

    ensure_dir

    info "Fetching service account token from vault (biometric prompt expected)..."

    # This is the ONE biometric prompt. `op read` uses the desktop app integration.
    local sa_token
    sa_token=$(op read "$OP_SESSION_SA_REF" 2>&1) || {
        die "Failed to read SA token from vault. Ensure 1Password desktop integration is enabled.
Error: $sa_token"
    }

    # Validate we got something that looks like a token
    if [[ -z "$sa_token" || ${#sa_token} -lt 20 ]]; then
        die "Retrieved value doesn't look like a valid service account token."
    fi

    # Write token to session file with restrictive permissions
    (
        umask 077
        echo "$sa_token" > "$SESSION_TOKEN_FILE"
    )

    # Set initial expiry
    write_expiry

    # Quick validation: try listing vaults with the SA token
    local validation
    validation=$(OP_SERVICE_ACCOUNT_TOKEN="$sa_token" op vault list --format=json 2>&1) || {
        cleanup_session
        die "SA token validation failed. The token may be invalid or the service account may not have vault access.
Error: $validation"
    }

    local vault_count
    vault_count=$(echo "$validation" | python3 -c "import sys,json; print(len(json.load(sys.stdin)))" 2>/dev/null || echo "?")

    info "Session initialized. SA token validated ($vault_count vault(s) accessible)."
    info "Session expires after ${OP_SESSION_TIMEOUT}s of inactivity (rolling)."
    info "Use 'op-session.sh exec <cmd>' to run commands with secrets injected."
}

cmd_exec() {
    if [[ $# -eq 0 ]]; then
        die "Usage: op-session.sh exec <command> [args...]"
    fi

    local token
    token=$(load_token)

    # Run the command with OP_SERVICE_ACCOUNT_TOKEN injected ONLY into its env.
    # The token value never appears in the calling process's environment.
    OP_SERVICE_ACCOUNT_TOKEN="$token" "$@"
}

cmd_read() {
    if [[ $# -eq 0 ]]; then
        die "Usage: op-session.sh read <op://vault/item/field>"
    fi

    local token
    token=$(load_token)

    # Read a secret reference. Output goes to stdout.
    # The AGENT should pipe this directly into whatever needs it,
    # or better yet, use `exec` with `op run` instead.
    OP_SERVICE_ACCOUNT_TOKEN="$token" op read "$1"
}

cmd_status() {
    if ! is_session_valid; then
        echo "inactive"
        info "No active session."
        return 1
    fi

    local expiry now remaining
    expiry=$(read_expiry)
    now=$(now_epoch)
    remaining=$(( expiry - now ))

    echo "active"
    info "Session active. Expires in ${remaining}s ($(( remaining / 60 ))m)."
}

cmd_extend() {
    if ! is_session_valid; then
        die "No active session to extend."
    fi
    write_expiry
    info "Session timeout reset to ${OP_SESSION_TIMEOUT}s from now."
}

cmd_end() {
    cleanup_session
}

# ── Entrypoint ─────────────────────────────────────────────────────────────────

main() {
    local cmd="${1:-help}"
    shift || true

    case "$cmd" in
        init)    cmd_init "$@" ;;
        exec)    cmd_exec "$@" ;;
        read)    cmd_read "$@" ;;
        status)  cmd_status "$@" ;;
        extend)  cmd_extend "$@" ;;
        end)     cmd_end "$@" ;;
        help|-h|--help)
            echo "Usage: op-session.sh <init|exec|read|status|extend|end> [args...]"
            echo ""
            echo "Commands:"
            echo "  init              Authenticate (biometric) and start a session"
            echo "  exec <cmd...>     Run a command with OP_SERVICE_ACCOUNT_TOKEN injected"
            echo "  read <ref>        Read a secret reference (op://vault/item/field)"
            echo "  status            Check if session is active"
            echo "  extend            Reset the inactivity timeout"
            echo "  end               Destroy the session immediately"
            echo ""
            echo "Configuration (set in ~/.config/op-session/config):"
            echo "  OP_SESSION_SA_REF      op:// reference to your SA token"
            echo "  OP_SESSION_TIMEOUT     Inactivity timeout in seconds (default: 7200)"
            ;;
        *)
            die "Unknown command: $cmd. Run 'op-session.sh help' for usage."
            ;;
    esac
}

main "$@"
